name: ChatMon
version: '${project.version}'
main: me.elordenador.chatmon.ChatMon
api-version: 1.13
authors: [ elordenador ]
description: Chat Monitoring
commands:
  automod:
    description: Automod Main Command
    usage: /<command> (reload:disable:enable)
    permission: ChatMod.execute